### ISSUE TITLE
\wolfram

### ISSUE THREAD

**Issue by SingularisArt** [pilgrimlyieu/Snippets#8]
How can I use the \wolfram snippet? I've tried it as:
```tex
\[%
\wolfram
\int_{0}^{10} \frac{1}{x} \dx
\wolfram
.\]%
```
but that got it:
```tex
\[%
\text{$\$$Failed}
.\]%
```

I'm not sure on how to use it?

**Comment by pilgrimlyieu** [comment]
Mathematica, or Wolfram Script doesn't understand what does `\dx` mean, neither `d x`. You have to use `\, d` to declare that the `d` is a differential operator. Besides, you could to `\d x` to do the same thing since I've added a replacement rule for the case. See [`mdtex/extcal.py`](https://github.com/pilgrimlyieu/Snippets-Dependencies/blob/master/mdtex/extcal.py#L16).

![1](https://github.com/pilgrimlyieu/Snippets/assets/80107081/adc84a8b-5035-4097-ab9c-ab47d6d446ac)
![2](https://github.com/pilgrimlyieu/Snippets/assets/80107081/43adaeb3-3ea0-4d52-80a8-04d6eff344e6)
![3](https://github.com/pilgrimlyieu/Snippets/assets/80107081/7cbee617-0902-4c58-8c06-c3ed2dd6b4d2)

If you still want to use `\dx` or other, try to add a replacement rule in the [`pre_process_latex`](https://github.com/pilgrimlyieu/Snippets-Dependencies/blob/master/mdtex/extcal.py#L14-L17). For example, 

```python
def pre_process_latex(text):
	return re.sub(r'\\d(?=\w(?!\w))', r'\, d ', text)
```
